### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SlothyOne** [gigantessbeta/JoinTitle#1]
18.04 22:22:48 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::sendTitle()" (EXCEPTION) in "/JoinTitle-master/src/title/title" at line 30
18.04 22:22:48 [Server] Server thread/CRITICAL Could not execute task title\Send: Call to undefined method pocketmine\Player::sendTitle()
 RyanShaw2 joined the game

Could you fix this please?

**Comment by gigantessbeta** [comment]
You must change new SRC.

**Comment by MyDeacy** [comment]
You need to change the SRC to the latest one.
